'use client';

import { ConfigProvider, theme } from 'antd';

const LIGHT_TOKENS = {
  colorPrimary: '#6366f1',
  colorSuccess: '#22c55e',
  colorWarning: '#eab308',
  colorError: '#ef4444',
  colorInfo: '#6366f1',
  colorBgBase: '#ffffff',
  colorBgContainer: '#ffffff',
  colorBgElevated: '#ffffff',
  colorBgLayout: '#f5f5f5',
  colorBorder: '#e5e5e5',
  colorBorderSecondary: '#f0f0f0',
  colorTextBase: '#171717',
  colorTextSecondary: '#525252',
  colorTextTertiary: '#a3a3a3',
  colorTextQuaternary: '#d4d4d4',
  borderRadius: 8,
  fontFamily: "'Source Serif 4', Georgia, 'Times New Roman', serif",
  fontSize: 14,
  fontSizeSM: 12,
  fontSizeLG: 16,
  fontSizeXL: 20,
  controlHeight: 40,
  controlHeightSM: 32,
  wireframe: false,
  boxShadow: '0 1px 3px 0 rgba(0,0,0,0.04)',
  boxShadowSecondary: '0 4px 6px -1px rgba(0,0,0,0.06), 0 2px 4px -2px rgba(0,0,0,0.04)',
};

const LIGHT_COMPONENTS = {
  Card: { paddingLG: 24, borderRadiusLG: 12, boxShadowTertiary: 'none', colorBorderSecondary: '#e5e5e5' },
  Table: {
    headerBg: '#fafafa',
    headerColor: '#525252',
    headerSortActiveBg: '#f0f0f0',
    headerSortHoverBg: '#f0f0f0',
    rowHoverBg: '#fafafa',
    borderColor: '#e5e5e5',
    headerBorderRadius: 8,
    cellPaddingBlock: 16,
    cellPaddingInline: 20,
  },
  Menu: {
    itemBg: 'transparent',
    itemBorderRadius: 6,
    horizontalItemSelectedColor: '#6366f1',
    itemColor: '#525252',
    itemHoverBg: 'rgba(99,102,241,0.04)',
    itemHoverColor: '#171717',
    subMenuItemBg: 'transparent',
    itemSelectedBg: 'rgba(99,102,241,0.08)',
    itemSelectedColor: '#6366f1',
    itemMarginInline: 4,
    itemPaddingInline: 12,
  },
  Tag: { defaultBg: '#f5f5f5', defaultColor: '#525252', borderRadiusSM: 6, fontSizeSM: 11 },
  Button: {
    fontWeight: 500,
    primaryShadow: 'none',
    controlHeight: 40,
    defaultBorderColor: '#d4d4d4',
    primaryColor: '#ffffff',
    borderRadius: 8,
    contentFontSizeSM: 13,
    contentFontSizeLG: 14,
    borderColorDisabled: '#e5e5e5',
    defaultGhostBorderColor: '#6366f1',
    defaultGhostColor: '#6366f1',
  },
  Input: {
    controlHeight: 44,
    addonBg: '#f5f5f5',
    borderRadius: 8,
    activeBorderColor: '#6366f1',
    hoverBorderColor: '#d4d4d4',
    paddingInline: 16,
    paddingBlock: 12,
    colorBgContainer: '#ffffff',
    colorBgContainerDisabled: '#f5f5f5',
  },
  Modal: { contentBg: '#ffffff', headerBg: '#ffffff', titleColor: '#171717', borderRadiusLG: 16, paddingLG: 24 },
  Select: {
    controlHeight: 44,
    optionSelectedBg: '#f0f0f0',
    borderRadius: 8,
    optionActiveBg: '#f5f5f5',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
  },
  Layout: { headerBg: '#ffffff', headerHeight: 64, siderBg: '#000000', bodyBg: '#f5f5f5' },
  Tabs: {
    inkBarColor: '#6366f1',
    itemSelectedColor: '#6366f1',
    horizontalMargin: '0',
    itemHoverColor: '#171717',
    itemColor: '#525252',
    cardGutter: 4,
    cardBg: '#ffffff',
  },
  Switch: { trackMinWidth: 44, trackHeight: 24 },
  Collapse: {
    headerBg: 'transparent',
    contentBg: 'transparent',
    headerPadding: '16px 24px',
    contentPadding: '0 24px 20px',
    borderRadiusLG: 8,
  },
  DatePicker: {
    activeBorderColor: '#6366f1',
    hoverBorderColor: '#d4d4d4',
    activeShadow: '0 0 0 3px rgba(99, 102, 241, 0.15)',
    borderRadius: 8,
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
  },
  Dropdown: { borderRadiusLG: 12, paddingBlock: 8 },
  Message: { contentBg: '#ffffff', borderRadiusLG: 10 },
  Notification: { borderRadiusLG: 12 },
  Statistic: { titleFontSize: 12 },
  Progress: { remainingColor: '#e5e5e5' },
  Segmented: {
    itemSelectedBg: '#6366f1',
    itemSelectedColor: '#ffffff',
    trackBg: '#f0f0f0',
    itemColor: '#525252',
    itemHoverColor: '#171717',
  },
  Tooltip: { colorBgSpotlight: '#171717' },
  Popconfirm: { colorBgElevated: '#ffffff', borderRadiusLG: 12 },
  Badge: { indicatorHeight: 18 },
  Skeleton: { color: '#f0f0f0' },
  Spin: { dotSize: 32, dotSizeSM: 20, dotSizeLG: 48 },
};

export default function ThemeProvider({ children }: { children: React.ReactNode }) {
  return (
    <ConfigProvider
      theme={{
        algorithm: theme.defaultAlgorithm,
        cssVar: { key: 'taazi', prefix: '--ant-' },
        token: LIGHT_TOKENS,
        components: LIGHT_COMPONENTS,
      }}
    >
      {children}
    </ConfigProvider>
  );
}
